### ISSUE TITLE
Demonstration videos are private

### ISSUE THREAD

**Issue by Necior** [GothenburgBitFactory/gbf.org#4]
Both of the following YouTube videos are private:

* https://www.youtube.com/watch?v=mSPsRabNJhw (linked at https://gothenburgbitfactory.org/vitapi/);
* https://www.youtube.com/watch?v=1vo3x4WwQyM (linked at https://gothenburgbitfactory.org/vramsteg/).

**Comment by lauft** [comment]
Recovering was futile, I deleted those links.
